// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: proto/rand.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandType int32

const (
	RandType_ALL RandType = 0
)

// Enum value maps for RandType.
var (
	RandType_name = map[int32]string{
		0: "ALL",
	}
	RandType_value = map[string]int32{
		"ALL": 0,
	}
)

func (x RandType) Enum() *RandType {
	p := new(RandType)
	*p = x
	return p
}

func (x RandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rand_proto_enumTypes[0].Descriptor()
}

func (RandType) Type() protoreflect.EnumType {
	return &file_proto_rand_proto_enumTypes[0]
}

func (x RandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RandType.Descriptor instead.
func (RandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_rand_proto_rawDescGZIP(), []int{0}
}

type ReplyCodeType int32

const (
	ReplyCodeType_OK    ReplyCodeType = 0
	ReplyCodeType_ERROR ReplyCodeType = 1
)

// Enum value maps for ReplyCodeType.
var (
	ReplyCodeType_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	ReplyCodeType_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x ReplyCodeType) Enum() *ReplyCodeType {
	p := new(ReplyCodeType)
	*p = x
	return p
}

func (x ReplyCodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplyCodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rand_proto_enumTypes[1].Descriptor()
}

func (ReplyCodeType) Type() protoreflect.EnumType {
	return &file_proto_rand_proto_enumTypes[1]
}

func (x ReplyCodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplyCodeType.Descriptor instead.
func (ReplyCodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_rand_proto_rawDescGZIP(), []int{1}
}

type PrivateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	LambdaN   []byte `protobuf:"bytes,2,opt,name=LambdaN,proto3" json:"LambdaN,omitempty"`
	PhiN      []byte `protobuf:"bytes,3,opt,name=PhiN,proto3" json:"PhiN,omitempty"`
}

func (x *PrivateKey) Reset() {
	*x = PrivateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKey) ProtoMessage() {}

func (x *PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKey.ProtoReflect.Descriptor instead.
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return file_proto_rand_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PrivateKey) GetLambdaN() []byte {
	if x != nil {
		return x.LambdaN
	}
	return nil
}

func (x *PrivateKey) GetPhiN() []byte {
	if x != nil {
		return x.PhiN
	}
	return nil
}

type LocalPreParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaillierSK *PrivateKey `protobuf:"bytes,1,opt,name=PaillierSK,proto3" json:"PaillierSK,omitempty"`
	NTildei    []byte      `protobuf:"bytes,2,opt,name=NTildei,proto3" json:"NTildei,omitempty"`
	H1I        []byte      `protobuf:"bytes,3,opt,name=H1i,proto3" json:"H1i,omitempty"`
	H2I        []byte      `protobuf:"bytes,4,opt,name=H2i,proto3" json:"H2i,omitempty"`
	Alpha      []byte      `protobuf:"bytes,5,opt,name=Alpha,proto3" json:"Alpha,omitempty"`
	Beta       []byte      `protobuf:"bytes,6,opt,name=Beta,proto3" json:"Beta,omitempty"`
	P          []byte      `protobuf:"bytes,7,opt,name=P,proto3" json:"P,omitempty"`
	Q          []byte      `protobuf:"bytes,8,opt,name=Q,proto3" json:"Q,omitempty"`
}

func (x *LocalPreParams) Reset() {
	*x = LocalPreParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalPreParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPreParams) ProtoMessage() {}

func (x *LocalPreParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPreParams.ProtoReflect.Descriptor instead.
func (*LocalPreParams) Descriptor() ([]byte, []int) {
	return file_proto_rand_proto_rawDescGZIP(), []int{1}
}

func (x *LocalPreParams) GetPaillierSK() *PrivateKey {
	if x != nil {
		return x.PaillierSK
	}
	return nil
}

func (x *LocalPreParams) GetNTildei() []byte {
	if x != nil {
		return x.NTildei
	}
	return nil
}

func (x *LocalPreParams) GetH1I() []byte {
	if x != nil {
		return x.H1I
	}
	return nil
}

func (x *LocalPreParams) GetH2I() []byte {
	if x != nil {
		return x.H2I
	}
	return nil
}

func (x *LocalPreParams) GetAlpha() []byte {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *LocalPreParams) GetBeta() []byte {
	if x != nil {
		return x.Beta
	}
	return nil
}

func (x *LocalPreParams) GetP() []byte {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *LocalPreParams) GetQ() []byte {
	if x != nil {
		return x.Q
	}
	return nil
}

type RandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type RandType `protobuf:"varint,1,opt,name=type,proto3,enum=tssrand.RandType" json:"type,omitempty"`
}

func (x *RandRequest) Reset() {
	*x = RandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandRequest) ProtoMessage() {}

func (x *RandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandRequest.ProtoReflect.Descriptor instead.
func (*RandRequest) Descriptor() ([]byte, []int) {
	return file_proto_rand_proto_rawDescGZIP(), []int{2}
}

func (x *RandRequest) GetType() RandType {
	if x != nil {
		return x.Type
	}
	return RandType_ALL
}

type RandReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ReplyCodeType   `protobuf:"varint,1,opt,name=code,proto3,enum=tssrand.ReplyCodeType" json:"code,omitempty"`
	Msg  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *LocalPreParams `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RandReply) Reset() {
	*x = RandReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rand_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandReply) ProtoMessage() {}

func (x *RandReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rand_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandReply.ProtoReflect.Descriptor instead.
func (*RandReply) Descriptor() ([]byte, []int) {
	return file_proto_rand_proto_rawDescGZIP(), []int{3}
}

func (x *RandReply) GetCode() ReplyCodeType {
	if x != nil {
		return x.Code
	}
	return ReplyCodeType_OK
}

func (x *RandReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RandReply) GetData() *LocalPreParams {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_rand_proto protoreflect.FileDescriptor

var file_proto_rand_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x74, 0x73, 0x73, 0x72, 0x61, 0x6e, 0x64, 0x22, 0x58, 0x0a, 0x0a, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x61, 0x6d, 0x62, 0x64,
	0x61, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4c, 0x61, 0x6d, 0x62, 0x64, 0x61,
	0x4e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x68, 0x69, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x50, 0x68, 0x69, 0x4e, 0x22, 0xc9, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50,
	0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x33, 0x0a, 0x0a, 0x50, 0x61, 0x69, 0x6c,
	0x6c, 0x69, 0x65, 0x72, 0x53, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74,
	0x73, 0x73, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x0a, 0x50, 0x61, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x72, 0x53, 0x4b, 0x12, 0x18, 0x0a,
	0x07, 0x4e, 0x54, 0x69, 0x6c, 0x64, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x4e, 0x54, 0x69, 0x6c, 0x64, 0x65, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x48, 0x31, 0x69, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x48, 0x31, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x48, 0x32, 0x69,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x48, 0x32, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x41,
	0x6c, 0x70, 0x68, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x41, 0x6c, 0x70, 0x68,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x42, 0x65, 0x74, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x50, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x50, 0x12, 0x0c, 0x0a, 0x01, 0x51, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x51, 0x22, 0x34, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x74, 0x73, 0x73, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x76, 0x0a, 0x09, 0x52, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74, 0x73, 0x73, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x74, 0x73, 0x73, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x50, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a,
	0x13, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x4c, 0x4c, 0x10, 0x00, 0x2a, 0x22, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x3d, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x64,
	0x12, 0x35, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x74, 0x73,
	0x73, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x74, 0x73, 0x73, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rand_proto_rawDescOnce sync.Once
	file_proto_rand_proto_rawDescData = file_proto_rand_proto_rawDesc
)

func file_proto_rand_proto_rawDescGZIP() []byte {
	file_proto_rand_proto_rawDescOnce.Do(func() {
		file_proto_rand_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rand_proto_rawDescData)
	})
	return file_proto_rand_proto_rawDescData
}

var file_proto_rand_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_rand_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rand_proto_goTypes = []interface{}{
	(RandType)(0),          // 0: tssrand.RandType
	(ReplyCodeType)(0),     // 1: tssrand.ReplyCodeType
	(*PrivateKey)(nil),     // 2: tssrand.PrivateKey
	(*LocalPreParams)(nil), // 3: tssrand.LocalPreParams
	(*RandRequest)(nil),    // 4: tssrand.RandRequest
	(*RandReply)(nil),      // 5: tssrand.RandReply
}
var file_proto_rand_proto_depIdxs = []int32{
	2, // 0: tssrand.LocalPreParams.PaillierSK:type_name -> tssrand.PrivateKey
	0, // 1: tssrand.RandRequest.type:type_name -> tssrand.RandType
	1, // 2: tssrand.RandReply.code:type_name -> tssrand.ReplyCodeType
	3, // 3: tssrand.RandReply.data:type_name -> tssrand.LocalPreParams
	4, // 4: tssrand.Rand.GetRand:input_type -> tssrand.RandRequest
	5, // 5: tssrand.Rand.GetRand:output_type -> tssrand.RandReply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_rand_proto_init() }
func file_proto_rand_proto_init() {
	if File_proto_rand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalPreParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rand_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rand_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rand_proto_goTypes,
		DependencyIndexes: file_proto_rand_proto_depIdxs,
		EnumInfos:         file_proto_rand_proto_enumTypes,
		MessageInfos:      file_proto_rand_proto_msgTypes,
	}.Build()
	File_proto_rand_proto = out.File
	file_proto_rand_proto_rawDesc = nil
	file_proto_rand_proto_goTypes = nil
	file_proto_rand_proto_depIdxs = nil
}
